#!/bin/bash

scriptDir=$(dirname "$0")

$scriptDir/../generateChangelog.sh
git add CHANGELOG.md

$scriptDir/../format.sh

# readd the files that were formatted
stagedFiles=$(git diff --cached --name-only --diff-filter=ACM)
git add $stagedFiles