build_image:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY/universumgames/mic-projekt:latest .
    - docker push $CI_REGISTRY/universumgames/mic-projekt

build:
  stage: build
  script:
    - pio run -e esp32-c3-devkitc-02
  artifacts:
    paths:
      - .pio/build/esp32dev/firmware.bin