image: registry.ide3.de/universumgames/mic-projekt/pio_build_esp32

default:
  cache:
    key: pio toolchain cache
    paths:
      - .platformio/packages

build:
  stage: build
  script:
    - echo $CI_PROJECT_PATH
    - echo $PLATFORMIO_PACKAGES_DIR
    - pio run -e esp32-c3-devkitc-02
  variables:
    PLATFORMIO_PACKAGES_DIR: "${CI_PROJECT_PATH}.platformio/packages"
  artifacts:
    paths:
      - .pio/build/esp32-c3-devkitc-02/firmware.bin

test:
  stage: test
  script:
    - pio test -e native
  variables:
    PLATFORMIO_PACKAGES_DIR: "${CI_PROJECT_PATH}.platformio/packages"
