image: $CI_REGISTRY_IMAGE:latest

default:
  cache:
    key: pio toolchain cache
    paths:
      - .platformio
      - .platformio

build:
  stage: build
  script:
    - pio run -e esp32-c3-devkitc-02
  variables:
    PLATFORMIO_PACKAGES_DIR: "${CI_PROJECT_DIR}/.platformio/packages"
  artifacts:
    paths:
      - .pio/build/esp32-c3-devkitc-02/firmware.bin

unit_tests:
  stage: test
  script:
    - pio test -e native_x64
  variables:
    PLATFORMIO_PACKAGES_DIR: "${CI_PROJECT_PATH}.platformio/packages"

check:
  stage: test
  script:
    - pio check -e esp32-c3-devkitc-02
  variables:
    PLATFORMIO_PACKAGES_DIR: "${CI_PROJECT_PATH}.platformio/packages"