image: registry.ide3.de/universumgames/mic-projekt/pio_build_esp32

build:
  stage: build
  script:
    - pio run -e esp32-c3-devkitc-02
  artifacts:
    paths:
      - .pio/build/esp32-c3-devkitc-02/firmware.bin