image: registry.ide3.de/universumgames/mic-projekt/pio_build_esp32

default:
  cache:
    key: pio toolchain cache
    paths:
      - /root/.platformio/

build:
  stage: build
  script:
    - pio run -e esp32-c3-devkitc-02
  artifacts:
    paths:
      - .pio/build/esp32-c3-devkitc-02/firmware.bin

test:
  stage: test
  script:
    - pio test -e native