@startgantt
Project starts 2024-10-04
[Kickoff] happens at 2024-10-04
[KICAD Workshop] happens at 2024-10-11
[M1: BOM & Schaltplan] happens at 2024-10-18
[1 Minute Madness] happens at 2024-10-18
[M2: PCB] happens at 2024-11-15
[Challenge Key Lab] happens at 2024-12-06
[M3: Software] happens at 2024-12-06
[Challenge Bomb Lab] happens at 2025-01-10
[M4: System] happens at 2025-01-10
[Engingeering Days] happens at 2025-01-24
@endgantt

